import React from 'react';
import { ControlLoop } from '../types/gcu1.types';

interface ControlLoopDiagramProps {
  loop: ControlLoop;
  }

  export const ControlLoopDiagram: React.FC<ControlLoopDiagramProps> = ({ loop }) => {
    return (
        <div className="bg-slate-900 rounded-lg shadow p-6 text-white border border-slate-700">
              <h3 className="text-lg font-bold mb-6 text-center text-blue-400">{loop.name} Architecture</h3>
                    
                          <div className="flex flex-col md:flex-row items-center justify-between gap-4 text-sm">
                                  {/* Reference */}
                                          <div className="flex flex-col items-center">
                                                    <div className="bg-blue-600 px-4 py-3 rounded-lg shadow-lg border border-blue-400 w-32 text-center">
                                                                <div className="text-xs text-blue-200">Reference</div>
                                                                            <div className="font-mono font-bold text-lg">{loop.referenceValue}</div>
                                                                                      </div>
                                                                                                <div className="text-xs text-slate-400 mt-1">Setpoint</div>
                                                                                                        </div>

                                                                                                                <div className="text-slate-500 text-2xl">→</div>

                                                                                                                        {/* Summing Junction */}
                                                                                                                                <div className="flex flex-col items-center">
                                                                                                                                          <div className="w-12 h-12 rounded-full border-2 border-white flex items-center justify-center font-bold text-lg bg-slate-800">
                                                                                                                                                      Σ
                                                                                                                                                                </div>
                                                                                                                                                                          <div className="text-xs text-slate-400 mt-1">Error: {loop.errorSignal.toFixed(1)}</div>
                                                                                                                                                                                  </div>

                                                                                                                                                                                          <div className="text-slate-500 text-2xl">→</div>

                                                                                                                                                                                                  {/* Controller */}
                                                                                                                                                                                                          <div className="flex flex-col items-center">
                                                                                                                                                                                                                    <div className="bg-purple-600 px-4 py-3 rounded-lg shadow-lg border border-purple-400 w-32 text-center">
                                                                                                                                                                                                                                <div className="text-xs text-purple-200">GCU Controller</div>
                                                                                                                                                                                                                                            <div className="font-mono font-bold text-lg">PID</div>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                <div className="text-xs text-slate-400 mt-1">Output: {loop.controlOutput.toFixed(1)}</div>
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                <div className="text-slate-500 text-2xl">→</div>

                                                                                                                                                                                                                                                                                        {/* Actuator & Plant */}
                                                                                                                                                                                                                                                                                                <div className="flex flex-col items-center">
                                                                                                                                                                                                                                                                                                          <div className="bg-emerald-600 px-4 py-3 rounded-lg shadow-lg border border-emerald-400 w-32 text-center">
                                                                                                                                                                                                                                                                                                                      <div className="text-xs text-emerald-200">Actuator / Plant</div>
                                                                                                                                                                                                                                                                                                                                  <div className="font-mono font-bold text-lg">IDG / Exciter</div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                            <div className="text-slate-500 text-2xl">→</div>

                                                                                                                                                                                                                                                                                                                                                                    {/* Feedback */}
                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-col items-center relative">
                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-amber-600 px-4 py-3 rounded-lg shadow-lg border border-amber-400 w-32 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-xs text-amber-200">Feedback Sensor</div>
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="font-mono font-bold text-lg">CT / PT</div>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Feedback Arrow going back */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="hidden md:block absolute -bottom-8 left-1/2 transform -translate-x-1/2 text-slate-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <svg width="100" height="40" className="rotate-180">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d="M 10 10 L 90 10 L 90 30" fill="none" stroke="currentColor" strokeWidth="2" markerEnd="url(#arrowhead)"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-8 text-xs text-slate-400 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * This diagram represents the closed-loop causality. A change in Load affects the Plant, altering Feedback, which generates an Error signal, prompting the Controller to adjust the Actuator.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };