import React from 'react';
import { FeedbackSignal } from '../types/gcu1.types';

interface FeedbackSignalViewerProps {
  signals: FeedbackSignal[];
    loopName: string;
    }

    export const FeedbackSignalViewer: React.FC<FeedbackSignalViewerProps> = ({ signals, loopName }) => {
      const getStatusColor = (status: string) => {
          switch (status) {
                case 'normal': return 'bg-green-100 text-green-800 border-green-200';
                      case 'warning': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
                            case 'fault': return 'bg-red-100 text-red-800 border-red-200';
                                  default: return 'bg-slate-100 text-slate-800';
                                      }
                                        };

                                          return (
                                              <div className="bg-white rounded-lg shadow p-4 border border-slate-200">
                                                    <h3 className="text-sm font-bold text-slate-800 mb-3 border-b pb-2">{loopName}</h3>
                                                          <div className="overflow-x-auto">
                                                                  <table className="w-full text-sm text-left">
                                                                            <thead className="text-xs text-slate-500 uppercase bg-slate-50">
                                                                                        <tr>
                                                                                                      <th className="px-3 py-2">Signal</th>
                                                                                                                    <th className="px-3 py-2">Current</th>
                                                                                                                                  <th className="px-3 py-2">Nominal</th>
                                                                                                                                                <th className="px-3 py-2">Unit</th>
                                                                                                                                                              <th className="px-3 py-2">Status</th>
                                                                                                                                                                          </tr>
                                                                                                                                                                                    </thead>
                                                                                                                                                                                              <tbody>
                                                                                                                                                                                                          {signals.map((signal) => (
                                                                                                                                                                                                                        <tr key={signal.id} className="border-b hover:bg-slate-50 transition-colors">
                                                                                                                                                                                                                                        <td className="px-3 py-2 font-medium text-slate-700">{signal.name}</td>
                                                                                                                                                                                                                                                        <td className="px-3 py-2 font-mono font-bold text-slate-900">
                                                                                                                                                                                                                                                                          {signal.currentValue.toFixed(1)}
                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                          <td className="px-3 py-2 font-mono text-slate-500">{signal.nominalValue}</td>
                                                                                                                                                                                                                                                                                                                          <td className="px-3 py-2 text-slate-500">{signal.unit}</td>
                                                                                                                                                                                                                                                                                                                                          <td className="px-3 py-2">
                                                                                                                                                                                                                                                                                                                                                            <span className={`px-2 py-1 rounded-full text-xs font-semibold border ${getStatusColor(signal.status)}`}>
                                                                                                                                                                                                                                                                                                                                                                                {signal.status.toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };